# Generated by Django 4.1.6 on 2023-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='marka')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('weight', models.FloatField()),
                ('image', models.ImageField(default='drones/indir.jpeg', upload_to='drones/%Y/%m/%d/')),
                ('avaliable', models.BooleanField(default=True)),
            ],
        ),
    ]
