# Generated by Django 4.1.6 on 2023-02-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='image',
            field=models.ImageField(default='drones/indir.jpeg', upload_to='drones/%Y/%m/%d/', verbose_name='fotoğraf'),
        ),
    ]
