# Generated by Django 4.1.6 on 2023-02-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_alter_drone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='image',
            field=models.ImageField(default='drones/indir.jpeg', upload_to='', verbose_name='fotoğraf'),
        ),
    ]
