# Generated by Django 4.1.7 on 2023-02-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drones.category'),
        ),
    ]
